services:
  easytier-web:
    image: heavrnl/easytier-web:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"         # Web UI
      - "11211:11211"       # API Server
      - "22020:22020/udp"   # Config Server
    volumes:
      - ./easytier_data:/data
    restart: unless-stopped

volumes:
  easytier_data:
